### ISSUE TITLE
udc-core: couldn't find an available UDC - added [ubq_gadget] 

### ISSUE THREAD

**Issue by arshadyab** [airbus-seclab/usbq_core#3]
Getting an error while mounting the ubqcore driver on USB drive. Need your help to resolve this issue 
Running on Linux beaglebone 4.14.108-ti-r113 #1 SMP PREEMPT  armv7l GNU/Linux

root@beaglebone:/usbq_core# echo '1-1:1.0' > /sys/bus/usb/drivers/ubq_driver/bind
root@beaglebone:/usbq_core# dmesg | tail
[ 2082.592616] *** NEW descriptor 05
[ 2082.592628] [ 15] GADGET  parse_init_pkt(0706): 
[ 2082.592633] New EP:number:1 type:BULK dir:IN bEndpointAddress:0x81 interval:0 wMaxPacketSize:512
[ 2082.592640] [ 15] GADGET check_descriptor_header(0550): 
[ 2082.592644] HEADER: 05
[ 2082.592651] [ 15] GADGET  parse_init_pkt(0691): 
[ 2082.592655] *** NEW descriptor 05
[ 2082.592665] [ 15] GADGET  parse_init_pkt(0706): 
[ 2082.592670] New EP:number:2 type:BULK dir:OUT bEndpointAddress:0x02 interval:0 wMaxPacketSize:512
[ 2082.592680] udc-core: couldn't find an available UDC - added [ubq_gadget] to list of pending drivers
root@beaglebone:/usbq_core#

**Comment by postyrus** [comment]
Hi Arshadyab,

Did you end up getting this to work? I was able to resolve this problem by booting the BBB without the am335x....sh script in /opt/scripts/boot. I would then log into the unit using ethernet instead. 

I then recompiled usbq_core with the different IP address in driver.c and the loaded it. It now appears to work ok on the BBB when I run the usbq program from my host PC however now I get a unknown device in Windows with vendorID 0000 and productID 0003. I think the vendor and product IDs aren't coming through when the device gets enumerated.
